project_id = "aurcamruwoameygvyecv"

[functions.handle-rsvp]
verify_jwt = false

[functions.send-event-reminders]
verify_jwt = false

[functions.notify-event-cancellation]
verify_jwt = false

[functions.handle-child-registration]
verify_jwt = false

[functions.vms-daily-notifications]
verify_jwt = false

[functions.task-reminders]
verify_jwt = false
